import React from "react";
import { Button, Modal } from "@/src/components";

const TermsModal = ({ isOpen, onClose, onAgree }) => {
  return (
    <Modal onClose={onClose} isOpen={isOpen}>
      <h2 className="text-gray-600 font-bold text-[24px] text-center mb-4">
        TERMS OF SERVICE
      </h2>
      <div className="flex flex-col md:w-[600px] lg:w-[900px] w-full gap-5 max-h-[500px]
      scroll-container overflow-y-auto">
        <p className="text-gray-600 mb-4">
        These Terms of Service govern your use of the website located at https://www.visageverse.com and any related services provided by VisageVerse.
By accessing https://www.visageverse.com, you agree to abide by these Terms of Service and to comply with all applicable laws and regulations. If you do not agree with these Terms of Service, you are prohibited from using or accessing this website or using any other services provided by VisageVerse.
We, VisageVerse, reserve the right to review and amend any of these Terms of Service at our sole discretion. Upon doing so, we will update this page. Any changes to these Terms of Service will take effect immediately from the date of publication.
These Terms of Service were last updated on March 10, 2024.
Limitations of Use
By using this website, you warrant on behalf of yourself, your users, and other parties you represent that you will not:
modify, copy, prepare derivative works of, decompile, or reverse engineer any materials and software contained on this website;
remove any copyright or other proprietary notations from any materials and software on this website;
transfer the materials to another person or "mirror" the materials on any other server;
knowingly or negligently use this website or any of its associated services in a way that abuses or disrupts our networks or any other service VisageVerse provides;
use this website or its associated services to transmit or publish any harassing, indecent, obscene, fraudulent, or unlawful material;
use this website or its associated services in violation of any applicable laws or regulations;
use this website in conjunction with sending unauthorized advertising or spam;
harvest, collect, or gather user data without the user’s consent; or
use this website or its associated services in such a way that may infringe the privacy, intellectual property rights, or other rights of third parties.
Intellectual Property
The intellectual property in the materials contained in this website are owned by or licensed to VisageVerse and are protected by applicable copyright and trademark law. We grant our users permission to download one copy of the materials for personal, non-commercial transitory use.
This constitutes the grant of a license, not a transfer of title. This license shall automatically terminate if you violate any of these restrictions or the Terms of Service, and may be terminated by VisageVerse at any time.
AI-Generated Content
VisageVerse offers an artificial intelligence (AI) image generation service, whereby users can upload a photograph of their face and receive a selection of images based on the submitted content. The service includes the option to select specific concepts for image creation or to utilize the Mystery Box feature for a variety of randomly selected concepts. By uploading a photograph to the VisageVerse platform, the user grants the company a non-exclusive, worldwide, royalty-free license to use, reproduce, modify, adapt, publish, and display the uploaded photograph for the sole purpose of providing the service detailed herein.
The images generated by the VisageVerse AI are derived from the user's uploaded photograph and selected concepts or the Mystery Box feature, leading to a wide range of outcomes. Due to the inherent nature of AI-generated content, VisageVerse cannot guarantee that all outcomes will align with user expectations. It is essential for users to acknowledge that the AI's interpretation of the provided photograph and concepts may result in significant variations in the generated images.
Mystery Boxes
VisageVerse's Mystery Box feature offers users an opportunity to receive AI-generated images based on a predetermined number of concepts, with each box tier varying in content and price. The purchase of a Mystery Box is final, with no refunds provided due to the digital and customized nature of the generated content. The service's Luck Multiplier, included in the Mystery Box feature, enhances the possibility of receiving unique or rare images but does not guarantee satisfaction or impact the total number of generated images. Users are permitted to use images obtained from Mystery Boxes for personal, non-commercial purposes only, with VisageVerse retaining all rights not expressly granted to the user under these terms.
Disclaimer and Limitations of Liability
Our website and the materials on our website are provided on an 'as is' basis. To the extent permitted by law, VisageVerse makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property, or other violation of rights.
In no event shall VisageVerse or its suppliers be liable for any consequential loss suffered or incurred by you or any third party arising from the use or inability to use this website or the materials on this website, even if VisageVerse or an authorized representative has been notified, orally or in writing, of the possibility of such damage.
In the context of this agreement, "consequential loss" includes any consequential loss, indirect loss, real or anticipated loss of profit, loss of benefit, loss of revenue, loss of business, loss of goodwill, loss of opportunity, loss of savings, loss of reputation, loss of use and/or loss or corruption of data, whether under statute, contract, equity, tort (including negligence), indemnity or otherwise.
Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
Accuracy of Materials
The materials appearing on our website are not comprehensive and are for general information purposes only. VisageVerse does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on this website, or otherwise relating to such materials or on any resources linked to this website. You should not rely solely on the said materials to make decisions, we advise you to consult other, more complete sources of information. You are solely responsible for the strict reliance on the materials posted on our website. We have the right to change the information on our website without prior notice and users are responsible to monitor said changes.
Additional Tools
Please note that our website may include third-party tools which are outside of our control. The access to said tools is provided on an 'as is' basis with no warranties, expressed or implied, and without any endorsement. We are not liable for the use of the third-party tools provided on our website. You are solely responsible for any risks associated with using said tools, we recommend reading the relevant third-party provider’s Terms of Service. VisageVerse has the right to offer new third-party tools in the future.
Links
VisageVerse has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement, approval or control by VisageVerse of the site. Use of any such linked site is at your own risk and we strongly advise you make your own investigations with respect to the suitability of those sites.
Inaccuracies and Mistakes
Please note that any content available on our website may contain typographical errors, inaccuracies, or mistakes related to the service’s description, pricing, promotion, and availability. We have the right to cancel or update any existing services should any information provided by us be proven inaccurate. Said information can be amended at any time without prior notice. Please note that we are not obligated to clarify any of the information related to our website and service, including pricing information, except as required by law.
Indemnification
You agree to defend, indemnify, and hold us harmless, including our subsidiaries, affiliates, and all of our respective officers, agents, partners, and employees, from and against any loss, damage, liability, claim, or demand, including reasonable attorneys’ fees and expenses, made by any third party due to or arising out of: (1) your Contributions; (2) use of the website; (3) breach of these Terms of Service; (4) any breach of your representations and warranties set forth in these Terms of Service; (5) your violation of the rights of a third party, including but not limited to intellectual property rights; or (6) any overt harmful act toward any other user of the website with whom you connected via the website. 
Notwithstanding the foregoing, we reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defense of such claims. We will use reasonable efforts to notify you of any such claim, action, or proceeding which is subject to this indemnification upon becoming aware of it.
Right to Terminate
We may suspend or terminate your right to use our website and terminate these Terms of Service immediately upon written notice to you for any breach of these Terms of Service.
Severance
Any term of these Terms of Service which is wholly or partially void or unenforceable is severed to the extent that it is void or unenforceable. The validity of the remainder of these Terms of Service is not affected.
Entire Agreement
These Terms of Service and any policies or operating rules posted by us on the website or with respect to the website constitute the entire agreement and understanding between you and us. Our failure to exercise or enforce any right or provision of these Terms of Service shall not operate as a waiver of such right or provision. These Terms of Service operate to the fullest extent permissible by law. We may assign any or all of our rights and obligations to others at any time. We shall not be responsible or liable for any loss, damage, delay, or failure to act caused by any cause beyond our reasonable control. 
If any provision or part of a provision of these Terms of Service is determined to be unlawful, void, or unenforceable, that provision or part of the provision is deemed severable from these Terms of Service and does not affect the validity and enforceability of any remaining provisions. There is no joint venture, partnership, employment, or agency relationship created between you and us as a result of these Terms of Service or use of the website. You agree that these Terms of Service will not be construed against us by virtue of having drafted them. You hereby waive any and all defenses you may have based on the electronic form of these Terms of Service and the lack of signing by the parties hereto to execute these Terms of Service.
Governing Law
These Terms of Service are governed by and construed in accordance with the laws of Mexico. You irrevocably submit to the exclusive jurisdiction of the courts in that location.
        </p>
      </div>
      <div className="flex justify-end gap-2 pt-3">
        <Button
          text="Cancel"
          classes="border-none"
          textClasses="text-black"
          onClick={onClose}
        />
        <Button
          text="Agree"
          classes="border-none"
          styles={{
            backgroundColor: "#7F3CF5",
            paddingLeft: 50,
            paddingRight: 50,
          }}
          onClick={() => {
            onAgree();
          }}
        />
      </div>
    </Modal>
  );
};

export {TermsModal};
